### ISSUE TITLE
Git ignored files on nvim-tree are too dark

### ISSUE THREAD

**Issue by manutepowa** [ChristianChiarulli/onedark.nvim#2]
Hi,

The theme is amazing.

I see that git ignored files are too dark.

As you can see in the screenshot below, the autocomplete highlight looks better.

Is this a problem with my kitty/nvim configuration ?

Thank you very much for your work

![image](https://github.com/ChristianChiarulli/onedark.nvim/assets/6350474/6e6b13d7-75f9-4ffd-90a0-c9f02a3f9593)

**Comment by ChristianChiarulli** [comment]
I made them slightly lighter, let me know if that helps

**Comment by manutepowa** [comment]
Yeah, looks great.

![image](https://github.com/ChristianChiarulli/onedark.nvim/assets/6350474/2979667d-5d11-4e63-8bba-079c8bf52403)
